
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppzjntadpeszygtzfcfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwempudGFkcGVzenlndHpmY2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDk3OTMsImV4cCI6MjA1NjU4NTc5M30.7iruXt_63zF7pbudd_oVwZFJYzSzL96PEdIbFaSi_xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
